name: First Workflow   // workflow name

on: workflow_dispatch  // manually trigger

jobs: 
  first-job:                         // job name
    runs-on: ubuntu-latest           // Define a runner
    steps:
      - name: Print greeting
        run:  echo "Hello world"
      - name: Print goodby
        run:  echo "Done - bye!"
