name: Label Issues ( Script Injection Fix Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          TITLE: ${{ github.event.issue.title }}
        run: |
          echo "First output"
          issue_title=$TITLE
          echo "Second output"
          echo $issue_title
          echo "Third output"
          if [[ "$issue_title" == *"bug"* ]]; then
            echo "Issue is about a bug!"
          else
            echo "Issue is not about a bug"
          fi
